### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by itdelatrisu**
* Changed some options text, disabled/~removed~ "Parallax", disabled scoreboard by default.
* Changed author/URLs to point to this repo.
* Changed `GameOpsu.VERSION` string format.
* ~Removed some text in the main menu.~

### CODE REVIEW

**Comment by fluddokt** [comment]
I don't really see the need to remove Parallax and the main menu text.

**Comment by itdelatrisu** [comment]
Parallax -- seems kind of silly if you don't have a mouse imo.

The main menu text takes up a lot of space on my phone (1920x1080) -- it seems like probably a general issue with font sizes being bigger than in the desktop version, so there's a lot of misaligned text.  Do you know why?

**Comment by fluddokt** [comment]
I still think its a fun effect so I kinda want to leave the option there even if its initially off.

Yes, it is because the font is actually bigger (1.5x at 2.0) due the "Scale certain UI elements" but the bars is based on the percentage of the height.

**Comment by itdelatrisu** [comment]
Okay, sounds good -- reverted those parts of it.

**Pull request merged**
